#!/bin/bash
################################################################################
# Moodle 5.1 System Optimization Script
# Version: 1.0.0
# Date: 2026-02-02
# Description: Optimizes PHP-FPM, Apache, and system settings for Moodle
################################################################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Logging
LOG_FILE="/var/log/moodle-optimization.log"
exec > >(tee -a "$LOG_FILE")
exec 2>&1

echo "======================================================================"
echo "Moodle System Optimization Script"
echo "Started: $(date)"
echo "======================================================================"

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}ERROR: Please run as root or with sudo${NC}"
    exit 1
fi

################################################################################
# Auto-detect RAM and calculate optimal settings
################################################################################

echo -e "\n${GREEN}[1/7] Detecting system resources...${NC}"

TOTAL_RAM_MB=$(free -m | awk '/^Mem:/{print $2}')
echo "Total RAM: ${TOTAL_RAM_MB} MB"

# Calculate PHP-FPM settings
SYSTEM_RAM_MB=800
AVAILABLE_RAM_MB=$((TOTAL_RAM_MB - SYSTEM_RAM_MB))
MEMORY_PER_PROCESS=200
MAX_CHILDREN=$((AVAILABLE_RAM_MB / MEMORY_PER_PROCESS))

# Bounds checking
[[ $MAX_CHILDREN -lt 5 ]] && MAX_CHILDREN=5
[[ $MAX_CHILDREN -gt 100 ]] && MAX_CHILDREN=100

START_SERVERS=$((MAX_CHILDREN / 5))
[[ $START_SERVERS -lt 2 ]] && START_SERVERS=2

MIN_SPARE=$((MAX_CHILDREN / 7))
[[ $MIN_SPARE -lt 1 ]] && MIN_SPARE=1

MAX_SPARE=$((MAX_CHILDREN / 3))
[[ $MAX_SPARE -lt 3 ]] && MAX_SPARE=3

echo "Calculated PHP-FPM settings:"
echo "  pm.max_children = $MAX_CHILDREN"
echo "  pm.start_servers = $START_SERVERS"
echo "  pm.min_spare_servers = $MIN_SPARE"
echo "  pm.max_spare_servers = $MAX_SPARE"

################################################################################
# Optimize PHP-FPM
################################################################################

echo -e "\n${GREEN}[2/7] Optimizing PHP-FPM configuration...${NC}"

PHP_FPM_CONF="/etc/php-fpm.d/www.conf"

# Backup original
if [ ! -f "${PHP_FPM_CONF}.original" ]; then
    cp "$PHP_FPM_CONF" "${PHP_FPM_CONF}.original"
    echo "Original config backed up to ${PHP_FPM_CONF}.original"
fi

# Apply optimizations
sed -i "s/^pm.max_children = .*/pm.max_children = $MAX_CHILDREN/" "$PHP_FPM_CONF"
sed -i "s/^pm.start_servers = .*/pm.start_servers = $START_SERVERS/" "$PHP_FPM_CONF"
sed -i "s/^pm.min_spare_servers = .*/pm.min_spare_servers = $MIN_SPARE/" "$PHP_FPM_CONF"
sed -i "s/^pm.max_spare_servers = .*/pm.max_spare_servers = $MAX_SPARE/" "$PHP_FPM_CONF"

# Add/update max_requests if not present
if ! grep -q "^pm.max_requests" "$PHP_FPM_CONF"; then
    sed -i '/^pm.max_spare_servers/a pm.max_requests = 500' "$PHP_FPM_CONF"
else
    sed -i "s/^pm.max_requests = .*/pm.max_requests = 500/" "$PHP_FPM_CONF"
fi

echo "PHP-FPM optimized"

################################################################################
# Configure PHP settings
################################################################################

echo -e "\n${GREEN}[3/7] Configuring PHP settings...${NC}"

PHP_INI="/etc/php.d/99-moodle.ini"

cat > "$PHP_INI" << EOF
; Moodle PHP Configuration
; Auto-generated by optimization script

; Memory and uploads
memory_limit = 384M
post_max_size = 100M
upload_max_filesize = 100M

; Timeouts
max_execution_time = 300
max_input_time = 300
max_input_vars = 5000

; OPcache
opcache.enable = 1
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 10000
opcache.revalidate_freq = 60
opcache.fast_shutdown = 1
opcache.save_comments = 0

; Session
session.save_handler = files
session.gc_probability = 1
session.gc_divisor = 100

; Error reporting
display_errors = Off
log_errors = On
error_log = /var/log/php-fpm/php-error.log

; Performance
realpath_cache_size = 4096K
realpath_cache_ttl = 600
EOF

echo "PHP settings configured"

################################################################################
# Configure Apache MPM Event
################################################################################

echo -e "\n${GREEN}[4/7] Configuring Apache MPM Event...${NC}"

# Ensure MPM Event is loaded
if ! grep -q "LoadModule mpm_event_module" /etc/httpd/conf.modules.d/00-mpm.conf; then
    sed -i 's/LoadModule mpm_prefork_module/#LoadModule mpm_prefork_module/' /etc/httpd/conf.modules.d/00-mpm.conf
    sed -i 's/#LoadModule mpm_event_module/LoadModule mpm_event_module/' /etc/httpd/conf.modules.d/00-mpm.conf
fi

# Create MPM configuration
MPM_CONF="/etc/httpd/conf.d/mpm.conf"

cat > "$MPM_CONF" << EOF
# Apache MPM Event Configuration
# Auto-generated for RAM: ${TOTAL_RAM_MB}MB

<IfModule mpm_event_module>
    ServerLimit              16
    StartServers             3
    MinSpareThreads          25
    MaxSpareThreads          75
    ThreadsPerChild          25
    MaxRequestWorkers        400
    MaxConnectionsPerChild   10000

    # KeepAlive
    KeepAlive On
    MaxKeepAliveRequests 100
    KeepAliveTimeout 5
</IfModule>
EOF

echo "Apache MPM Event configured"

################################################################################
# Configure SWAP if needed and not already present
################################################################################

echo -e "\n${GREEN}[5/7] Checking SWAP configuration...${NC}"

if [ "$TOTAL_RAM_MB" -le 8192 ]; then
    if ! swapon --show | grep -q "/swapfile"; then
        echo "Configuring SWAP..."

        # Calculate SWAP size
        if [ "$TOTAL_RAM_MB" -lt 2048 ]; then
            SWAP_SIZE_GB=$((TOTAL_RAM_MB * 2 / 1024))
        elif [ "$TOTAL_RAM_MB" -le 8192 ]; then
            SWAP_SIZE_GB=$((TOTAL_RAM_MB / 1024))
        fi

        [[ $SWAP_SIZE_GB -lt 1 ]] && SWAP_SIZE_GB=1
        [[ $SWAP_SIZE_GB -gt 8 ]] && SWAP_SIZE_GB=8

        SWAP_SIZE_MB=$((SWAP_SIZE_GB * 1024))

        echo "Creating ${SWAP_SIZE_GB}GB SWAP..."
        dd if=/dev/zero of=/swapfile bs=1M count=$SWAP_SIZE_MB status=progress
        chmod 600 /swapfile
        mkswap /swapfile
        swapon /swapfile

        # Make permanent
        if ! grep -q "/swapfile" /etc/fstab; then
            echo '/swapfile none swap sw 0 0' >> /etc/fstab
        fi

        # Set swappiness
        echo 'vm.swappiness=10' >> /etc/sysctl.conf
        sysctl -p

        echo "SWAP configured: ${SWAP_SIZE_GB}GB"
    else
        echo "SWAP already configured"
        swapon --show
    fi
else
    echo "RAM > 8GB, SWAP not necessary"
fi

################################################################################
# Setup memory monitoring
################################################################################

echo -e "\n${GREEN}[6/7] Setting up memory monitoring...${NC}"

cat > /usr/local/bin/memory-monitor.sh << 'MONITOR_SCRIPT'
#!/bin/bash
# Memory monitoring script for Moodle

LOG_FILE="/var/log/memory-monitor.log"
TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")

# Rotate log if > 10MB
if [ -f "$LOG_FILE" ] && [ $(stat -f%z "$LOG_FILE" 2>/dev/null || stat -c%s "$LOG_FILE") -gt 10485760 ]; then
    mv "$LOG_FILE" "${LOG_FILE}.old"
    gzip "${LOG_FILE}.old"
fi

# Log metrics
{
    echo "=== $TIMESTAMP ==="
    free -h
    echo "--- PHP-FPM: $(ps aux | grep php-fpm | grep -v grep | wc -l) processes"
    echo "--- Cron: $(ps aux | grep 'cron.php' | grep -v grep | wc -l) processes"
    echo "--- Apache: $(ps aux | grep httpd | grep -v grep | wc -l) processes"
    echo ""
} >> "$LOG_FILE"

# Alert if memory low
AVAILABLE_MB=$(free -m | awk '/^Mem:/{print $7}')
if [ $AVAILABLE_MB -lt 500 ]; then
    echo "WARNING: Low memory ($AVAILABLE_MB MB available)" >> "$LOG_FILE"
fi
MONITOR_SCRIPT

chmod +x /usr/local/bin/memory-monitor.sh

# Add to cron (hourly)
CRON_FILE="/etc/cron.d/memory-monitor"
echo "0 * * * * root /usr/local/bin/memory-monitor.sh" > "$CRON_FILE"
chmod 644 "$CRON_FILE"

echo "Memory monitoring configured (runs hourly)"

################################################################################
# Restart services
################################################################################

echo -e "\n${GREEN}[7/7] Restarting services...${NC}"

# Enable services
systemctl enable php-fpm
systemctl enable httpd

# Restart services
systemctl restart php-fpm
systemctl restart httpd

# Verify services
sleep 2

if systemctl is-active --quiet php-fpm; then
    echo -e "${GREEN}✓ PHP-FPM is running${NC}"
else
    echo -e "${RED}✗ PHP-FPM failed to start${NC}"
    systemctl status php-fpm
fi

if systemctl is-active --quiet httpd; then
    echo -e "${GREEN}✓ Apache is running${NC}"
else
    echo -e "${RED}✗ Apache failed to start${NC}"
    systemctl status httpd
fi

################################################################################
# Summary
################################################################################

echo -e "\n${GREEN}======================================================================"
echo "Optimization Complete!"
echo "======================================================================${NC}"

echo -e "\n📊 System Configuration:"
echo "  Total RAM: ${TOTAL_RAM_MB} MB"
echo "  PHP-FPM max_children: $MAX_CHILDREN"
if swapon --show | grep -q "/swapfile"; then
    SWAP_SIZE=$(swapon --show --noheadings | awk '{print $3}')
    echo "  SWAP: $SWAP_SIZE"
else
    echo "  SWAP: Not configured"
fi

echo -e "\n📈 Current Resource Usage:"
free -h

echo -e "\n📁 Configuration Files:"
echo "  PHP-FPM: $PHP_FPM_CONF"
echo "  PHP Settings: $PHP_INI"
echo "  Apache MPM: $MPM_CONF"
echo "  Monitor Log: /var/log/memory-monitor.log"

echo -e "\n🔍 Useful Commands:"
echo "  View memory log: sudo tail -f /var/log/memory-monitor.log"
echo "  PHP-FPM status: sudo systemctl status php-fpm"
echo "  Apache status: sudo systemctl status httpd"
echo "  Memory usage: free -h"
echo "  Top processes: ps aux --sort=-%mem | head -20"

echo -e "\n✅ Next Steps:"
echo "  1. Monitor /var/log/memory-monitor.log over the next week"
echo "  2. Check for OOM kills: sudo dmesg | grep -i 'out of memory'"
echo "  3. Adjust settings if needed based on actual usage"

echo -e "\nCompleted: $(date)"
echo "Log saved to: $LOG_FILE"

exit 0
